### PR TITLE
NF: user guide part II aka Part 4 of the workshop

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
@horea I have pushed what I have.  Feedback/improvements would be appreciated. Feel free to push directly I guess since reviewing PRs for ipython notebooks jsons isn't that much fun ;)

**Comment by bendichter** [comment]
After reading through this notebook, I am still confused about how to use datalad. Could you please provide examples?

**Comment by satra** [comment]
unless you use generated figures you can use`jupytext` on the hub to save it as both markdown and ipynb or just markdown. makes it easier for github reviews.

**Comment by satra** [comment]
a general note that this introduces some advanced concepts and i saw a couple of cells that involve typing code. for this workshop stay away from any code entry perhaps, or give them the answer.

**Comment by yarikoptic** [comment]
> a general note that this introduces some advanced concepts and i saw a couple of cells that involve typing code. for this workshop stay away from any code entry perhaps, or give them the answer.

hm... how to teach interacting with DANDI archive in Python, without making them coding in Python?  I point to an example code in the documentation, so it should be pretty much copy/paste .  Providing a complete answer would defeat the purpose of desiring it to be "hands on" (and not just "click the Run button")

**Pull request merged**
