### PR TITLE
000559

### PR DESCRIPTION
**Pull request by pauladkisson**
3 Notebooks reproduce figures from [Spontaneous behaviour is structured by reinforcement without explicit reward](https://www.nature.com/articles/s41586-022-05611-2) for conversion of Datta Lab data.

### CODE REVIEW

**Comment by bendichter** [comment]
Looks great, @pauladkisson ! Could you also please add an environment.yml file? See instructions in [the readme](https://github.com/dandi/example-notebooks/blob/master/README.md).

**Comment by bendichter** [comment]
@pauladkisson it looks like 2 of these files are empty

**Comment by pauladkisson** [comment]
> @pauladkisson it looks like 2 of these files are empty

Yes, hence why this PR is still in draft. For the figure 1D reproduction I am waiting for some missing data. For the figure S3 reproduction I am waiting for alignment data frames for the key points.

**Comment by pauladkisson** [comment]
@bendichter this is ready to go now!

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
@pauladkisson why is the metadata yaml file in here?

**Review by bendichter — CHANGES_REQUESTED** [review]
Could you add a README.md file that provides a description of this repo and a 1-2 sentence description of each notebook?

**Review by bendichter — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
@bendichter Is this ready for merge?

**Comment by yarikoptic** [comment]
note that this PR was merged while CI was red with not only unrelated but 1 related typo
```
./000559/dattalab/markowitz_gillis_nature_2023/analysis_configuration.toml:42: PROGRAMATICALLY ==> PROGRAMMATICALLY
```
... will fix up for that now

**Pull request merged**
