### PR TITLE
Update and extend (OPEN vs EMBARGOED; more data types and species mapped) stats for DANDI

### PR DESCRIPTION
**Pull request by yarikoptic**
Here are previews of some plots

image

image

### CODE REVIEW

**Comment by yarikoptic** [comment]
apparently codespell isn't happy -- will send fixes in a separate PR

**Review by satra — APPROVED** [review]

**Comment by bendichter** [comment]
This is now really only meaningful if the user that runs it has admin privileges. For example, if I run this I only get 4 embargoed dandisets, since I am only an owner of 4. Given that, I think I'd rather this be in a separate place, distinct from the DANDI summary commands that can be run by any user.

**Comment by yarikoptic** [comment]
Well, I didn't realize this would be of interest to a regular user.

"separate place" == "duplication" == divergence of implementations etc. So I would really hope that we could avoid that.

Let me offer two solutions in the order of my preference ;)
- Just provide documentation/description summarizing what @bendichter mention
- make it by default without embargoed but possible to enable/change the style happen one of us decides to use it for stats

NB thinking out loud... ideally we should just make this notebook run e.g. weekly and place those images somewhere on the website for up-to-date informatio

**Comment by satra** [comment]
i may have posted an issue to generate this dashboard directly on top of django, i.e. by our backend :)

**Comment by yarikoptic** [comment]
ok, I have added explicit `embargoed = True` and a comment  so anon users could flip it if desired. Verified that it still works.

I rebased  and reran so it is uptodate ATM. I addressed typo directly in master, rebased again...

@bendichter -- are you ok with this? (@satra already blessed PR)

**Comment by yarikoptic** [comment]
here is how that cell looks like now
image

**Review by bendichter — APPROVED** [review]
lgtm

**Comment by yarikoptic** [comment]
oh, it was approved! Let's proceed!

**Pull request merged**
