### PR TITLE
adding notebooks for #000055

### PR DESCRIPTION
**Pull request by bendichter**
@satra how about this as a way for users to share data pertaining to their dandisets? Here I have created a directory 000055, which can contain multiple notebooks for that dandiset.

### CODE REVIEW

**Comment by satra** [comment]
@bendichter - this is a reasonable approach in the short term. 

in the longer term, users should be able to do this in their own repos, mint a doi via zenodo, link it to a dandiset.  we could then have something like a curated set of repos per dandiset.

`dandianalytics/<dandisetid>/<org_or_lab_name>/<reponame>` where the reponame could be a submodule or something.

**Comment by bendichter** [comment]
I was originally thinking about published notebooks that are published by the lab in association with their own dandiset, but I see how another layer would nicely allow other labs to also publish their own analyses on public dandisets, or how the same lab could publish additional analyses. Would you like to create that file hierarchy here?

**Comment by satra** [comment]
sure. just create the hierarchy inside 000055

**Comment by bendichter** [comment]
waiting on resolution of https://github.com/dandi/dandi-cli/issues/672

**Comment by satra** [comment]
let's merge it and then check it out on dandi. may be useful to write a little blog post about this on the dandiarchive page.

**Pull request merged**
