### PR TITLE
Adding notebook for dandiset `000727`

### PR DESCRIPTION
**Pull request by h-mayorquin**
As requested by @bendichter. A simple notebook explaining how to read data and showing some processing and plots.

### CODE REVIEW

**Comment by yarikoptic** [comment]
would you be so kind to rebase this PR so we get codespell to check it. If it is red - please attend to typos it might have found.  @bendichter  - would you be able to provide review for this contribution (as the original motivator ;) )?

**Comment by bendichter** [comment]
This might be easier using remfile instead of fsspec:

```python
from h5py import File
from pynwb import NWBHDF5IO
import remfile

file = remfile.File(url)
h5_file = File(file, "r")

io = NWBHDF5IO(file=h5_file, load_namespaces=True)
nwbfile = io.read()
nwbfile
```

Could you also include a call to `nwbfile` at the end so that the interactive HTML repr is displayed?

Doing so reveals other neurodata objects. Could you demonstrate reading and plotting one of the spatial series in FicTrac?

**Comment by bendichter** [comment]
You can utilize the new `TimeSeries.get_timestamps()` method

**Comment by h-mayorquin** [comment]
OK:
* I added a showcase of how to extract the FicTrac data.
* Removed the embargo logic at the beginning as this data is now released.
* Changed to remfile.
* Merged with the latest changes in master.

**Review by bendichter — APPROVED** [review]

**Pull request merged**
