### PR TITLE
Add 001075 example figure

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Reproduction of Fig 1d from https://www.nature.com/articles/s41586-023-06683-4#data-availability

A small number of traces differ and I will go over some possible reasons why with the group when I meet with them tomorrow

Given that 90% of the traces match, I'd say it's pretty trustworthy though

Ran out of time to complete the top axis stimulation target labels (patterned optogenetic data only specifies the approximate VOXEL that was targeted - finding the nearest ROI with a NeuroPAL label is certainly possible from the data though - probably a good exercise for a NeurodataRehack)

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
GitHub rendered view: https://github.com/dandi/example-notebooks/blob/10ee743f7a0a2dce8d33a6caa5679e491a84bf60/001075/001075_paper_figure_1d.ipynb

**Comment by CodyCBakerPhD** [comment]
> Ran out of time to complete the top axis stimulation target labels (patterned optogenetic data only specifies the approximate VOXEL that was targeted - finding the nearest ROI with a NeuroPAL label is certainly possible from the data though - probably a good exercise for a NeurodataRehack)

It looks like I do have a little bit more time left to spend next week though, so I'll also ask them what they'd prefer I try to polish in terms of figures (would enhance in a separate follow-up PR though)

**Comment by CodyCBakerPhD** [comment]
Converting to draft

TODO:
- add ogen target labels from source data and include in example notebook
- add README with a nav index for easy reference and sharing of how to access and cite dataset

**Comment by CodyCBakerPhD** [comment]
@bendichter OK, this is good to go!

**Review by bendichter — APPROVED** [review]

**Pull request merged**
