### PR TITLE
Create educational notebook based on Sargolini 2006

### PR DESCRIPTION
**Pull request by weiglszonja**
[Developer Days Project](https://docs.google.com/document/d/1wXELFWmKnJu30_PsZdGw1F3TE9WNyBOvGEFLa-9uMP4/edit#heading=h.og5k593eh9uy)

### CODE REVIEW

**Comment by bendichter** [comment]
@weiglszonja what still needs to be done with this PR? Is it ready for review?

**Comment by weiglszonja** [comment]
@bendichter Adding the cell layer information is missing currently, I checked the file that contains this, should not be hard to match it with the existing data. I can do it this week.

**Comment by weiglszonja** [comment]
@bendichter ready for review

**Comment by bendichter** [comment]
What is the purpose of 
```python
def pearson_cor_2arr(arr1, arr2):
    """ Calculating Pearson correlation for two arrays with the same shape and no NaN."""
    if not arr1.shape == arr2.shape:
        raise Exception("Both arrays should have the same shape")
    n = arr1.shape[0] * arr1.shape[1]
 
    numerator = n * np.sum(arr1 * arr2) - np.sum(arr1) * np.sum(arr2)
    denominator = (n * np.sum(arr1**2) - np.sum(arr1)**2)**0.5 * (n * np.sum(arr2**2) - np.sum(arr2)**2)**0.5
    return numerator / denominator
```

I think this should be the same as `scipy.stats.pearsonr(arr1[:], arr2[:])[0]`

**Comment by weiglszonja** [comment]
> scipy.stats.pearsonr(arr1.flatten(), arr2.flatten())[0]

You're right, the arrays just have to be flattened, I don't remember why we didn't use `pearsonr` (let me know @djarecka if you do). Changed it in the notebook

**Comment by yarikoptic** [comment]
looks good to me. @bendichter do you give your blessing ? then please click big green button!

**Comment by djarecka** [comment]
> > What is the purpose of
> > ```python
> > def pearson_cor_2arr(arr1, arr2):
> >     """ Calculating Pearson correlation for two arrays with the same shape and no NaN."""
> >     if not arr1.shape == arr2.shape:
> >         raise Exception("Both arrays should have the same shape")
> >     n = arr1.shape[0] * arr1.shape[1]
> >  
> >     numerator = n * np.sum(arr1 * arr2) - np.sum(arr1) * np.sum(arr2)
> >     denominator = (n * np.sum(arr1**2) - np.sum(arr1)**2)**0.5 * (n * np.sum(arr2**2) - np.sum(arr2)**2)**0.5
> >     return numerator / denominator
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this should be the same as `scipy.stats.pearsonr(arr1[:], arr2[:])[0]`
> 
> You're right, the arrays just have to be flattened, I don't remember why we didn't use `pearsonr` (let me know @djarecka if you do). Changed it in the notebook

@weiglszonja - sorry, missed the question. Don't remember, why I created the function on my own, perhaps had some issues with the scipy function or wanted to compare. we can check if this gives the same results now.

**Comment by weiglszonja** [comment]
@djarecka no worries, I checked already.

**Comment by CodyCBakerPhD** [comment]
@weiglszonja @bendichter Any updated on this? Is this ready?

**Pull request merged**
