### PR TITLE
Leek mitu01 demo

### PR DESCRIPTION
**Pull request by LeeKamentsky**
Hi Satra,
Here's the first shot at a notebook that can read the MITU01 dataset. There's a few-line demo of segmenting blood vessels at the end. I could also do cell finding on the YO channel. LMK if there's anything that needs tweaking.
--Lee

### CODE REVIEW

**Comment by satra** [comment]
@LeeKamentsky - this looks like a nice example for people to get started with that dataset.

- perhaps you could display the slice next to the jpeg photo just to give people a sense of physical connection
- according to the json file it says slice thickness is `1000` which would mean 1mm, but the description of this notebook says 2mm. also given the slice numbers, i think juhyuk said about 180 slices, which at 2mm would be twice the size of an average brain. so i think 1mm may be the more correct slice thickness as noted in the json file. 
- perhaps some of the functions for working with this kind of data could be wrapped into the library @balbasty is building for this data: https://github.com/balbasty/mit-spim-io (we can help turn that into a maintained package)
- also i believe some of the dandiset traversal functions could use dandi library or inform the library (ping @jwodder and @yarikoptic )

**Comment by jwodder** [comment]
@LeeKamentsky Your code for interacting with the DANDI Archive can indeed make use of [the `dandi` library](https://github.com/dandi/dandi-cli)!  For example, the `get_asset_url()` function in `In [5]` can be rewritten as:

```python
from dandi.dandiapi import DandiAPIClient
from dandi.exceptions import NotFoundError

ASSET_URL_DB = {}

def get_asset_url(asset_id):
    """Return s3 url for a given asset id"""
    if asset_id in ASSET_URL_DB:
        return ASSET_URL_DB[asset_id]
    with DandiAPIClient.for_dandi_instance("dandi") as client:
        dandiset = client.get_dandiset("000108", "draft")
        asset = dandiset.get_asset(asset_id)
        try:
            asset_url = asset.get_content_url(r"s3\.amazonaws")
        except NotFoundError:
            return None
    ASSET_URL_DB[asset_id] = asset_url
    return asset_url
```

Consult [the documentation](https://dandi.readthedocs.io/en/latest/modref/dandiapi.html) or [the `dandi/dandiapi.py` source](https://github.com/dandi/dandi-cli/blob/master/dandi/dandiapi.py) for more information.

Note that the `/dandisets/:dandiset/versions/:version/assets/paths/` endpoint which much of your code uses is not supported by the `dandi` library, as it's intended only for use by the website's client-side rendering.  The closest equivalent in the library is `RemoteDandiset.get_assets_with_path_prefix()`, which uses the `/dandisets/:dandiset/versions/:version/assets/` endpoint instead.

**Comment by satra** [comment]
> `/dandisets/:dandiset/versions/:version/assets/paths/` endpoint which much of your code uses is not supported by the dandi library

@jwodder - any reason not to support this endpoint. it's a really useful endpoint to get any files at a given location of the tree.

**Comment by jwodder** [comment]
@satra What use case are you envisioning that isn't covered by `RemoteDandiset.get_assets_with_path_prefix()`?

**Comment by satra** [comment]
`path prefix` requires knowledge of the tree to use and the higher up the tree the more objects that are returned. while `paths` provides objects only at the given level of the tree. this allows even interactive navigation in the python terminal or in a jupyter notebook environment.

**Comment by LeeKamentsky** [comment]
I'm grepping for "RemoteDataset" and "get_assets_with_path_prefix" and can't find any reference in dandiapi. Are they somewhere else?

**Comment by jwodder** [comment]
@LeeKamentsky It's ["RemoteDandiset"](https://github.com/dandi/dandi-cli/blob/8313173b8c9930290c519313d9a2f53d4674b1c3/dandi/dandiapi.py#L435), not "RemoteDataset".  I don't know why you can't find [the `get_assets_with_path_prefix()` method](https://github.com/dandi/dandi-cli/blob/8313173b8c9930290c519313d9a2f53d4674b1c3/dandi/dandiapi.py#L713).

**Comment by LeeKamentsky** [comment]
I was looking in the wrong project: https://github.com/dandi/dandi-api not https://github.com/dandi/dandi-cli

**Comment by LeeKamentsky** [comment]
After trying out "get_assets_with_path_prefix", I can see @satra 's point of view. The API call returns everything under the tree, which when we move to NGFF is not going to be useful because of the number of files. I do need something akin to a directory listing ("assets/paths") to limit things just to the one level.

**Comment by LeeKamentsky** [comment]
I've added code to display the photo that accompanies the sample and I've used some Dandi API points. Might be some work to do still.

**Comment by satra** [comment]
i'm going to merge this in and then play with it on the hub.

**Pull request merged**
